import { brand } from '../config/brand'
import { supabase } from '../lib/supabase'
import { createNotification } from './notification.service'
import type {
  Invoice,
  InvoiceLine,
  InvoiceStatus,
  Quote,
  QuoteLine,
  QuoteStatus,
  QuoteTemplate,
  FiscalAttestation,
} from '../types'

// ---------------------------------------------------------------------------
// Filter types
// ---------------------------------------------------------------------------
export interface InvoiceFilters {
  search?: string
  status?: InvoiceStatus
  client_id?: string
  date_from?: string
  date_to?: string
  is_archived?: boolean
  page?: number
  pageSize?: number
}

export interface QuoteFilters {
  search?: string
  status?: QuoteStatus
  client_id?: string
  prospect_id?: string
  date_from?: string
  date_to?: string
  page?: number
  pageSize?: number
}

export interface PaginatedResult<T> {
  data: T[]
  count: number
  page: number
  pageSize: number
  totalPages: number
}

// ---------------------------------------------------------------------------
// getInvoices - Paginated list with optional filters
// ---------------------------------------------------------------------------
export async function getInvoices(
  filters: InvoiceFilters = {},
): Promise<PaginatedResult<Invoice>> {
  const {
    search,
    status,
    client_id,
    date_from,
    date_to,
    is_archived = false,
    page = 1,
    pageSize = 25,
  } = filters

  let query = supabase
    .from('invoices')
    .select('*, client:clients!client_id(id, first_name, last_name, company_name, siret, tva_number)', {
      count: 'exact',
    })

  query = query.eq('is_archived', is_archived)

  if (status) {
    query = query.eq('status', status)
  }

  if (client_id) {
    query = query.eq('client_id', client_id)
  }

  if (date_from) {
    query = query.gte('issue_date', date_from)
  }

  if (date_to) {
    query = query.lte('issue_date', date_to)
  }

  if (search) {
    query = query.or(
      `reference.ilike.%${search}%,title.ilike.%${search}%`,
    )
  }

  // Pagination
  const from = (page - 1) * pageSize
  const to = from + pageSize - 1

  query = query
    .order('issue_date', { ascending: false })
    .range(from, to)

  const { data, error, count } = await query

  if (error) throw error

  return {
    data: (data ?? []) as Invoice[],
    count: count ?? 0,
    page,
    pageSize,
    totalPages: Math.ceil((count ?? 0) / pageSize),
  }
}

// ---------------------------------------------------------------------------
// getInvoice - Single invoice with lines
// ---------------------------------------------------------------------------
export async function getInvoice(id: string): Promise<Invoice & { lines: InvoiceLine[] }> {
  const { data, error } = await supabase
    .from('invoices')
    .select(`
      *,
      client:clients!client_id(id, first_name, last_name, company_name, email, address_line1, postal_code, city, siret, tva_number),
      lines:invoice_lines(*)
    `)
    .eq('id', id)
    .single()

  if (error) throw error

  // Sort lines by sort_order
  if (data.lines) {
    data.lines.sort((a: InvoiceLine, b: InvoiceLine) => a.sort_order - b.sort_order)
  }

  return data as Invoice & { lines: InvoiceLine[] }
}

// ---------------------------------------------------------------------------
// createInvoice - Create invoice with its lines in a single transaction
// ---------------------------------------------------------------------------
export async function createInvoice(
  invoiceData: Omit<Invoice, 'id' | 'reference' | 'created_at' | 'updated_at'>,
  lines: Omit<InvoiceLine, 'id' | 'invoice_id' | 'created_at'>[],
): Promise<Invoice> {
  // Insert the invoice (reference is auto-generated by the DB trigger)
  const { data: invoice, error: invoiceError } = await supabase
    .from('invoices')
    .insert({ ...invoiceData, reference: '' })
    .select()
    .single()

  if (invoiceError) throw invoiceError

  // Insert all lines linked to the new invoice
  if (lines.length > 0) {
    const linesWithInvoiceId = lines.map((line) => ({
      ...line,
      invoice_id: invoice.id,
    }))

    const { error: linesError } = await supabase
      .from('invoice_lines')
      .insert(linesWithInvoiceId)

    if (linesError) {
      // Rollback: delete the orphaned invoice
      const { error: rollbackError } = await supabase.from('invoices').delete().eq('id', invoice.id)
      if (rollbackError) {
        console.error('[createInvoice] Rollback failed — orphaned invoice:', invoice.id, rollbackError.message)
      }
      throw linesError
    }
  }

  return invoice as Invoice
}

// ---------------------------------------------------------------------------
// updateInvoiceStatus
// ---------------------------------------------------------------------------
export async function updateInvoiceStatus(
  id: string,
  status: InvoiceStatus,
): Promise<Invoice> {
  const updateData: Record<string, unknown> = { status }

  // If marking as paid, record the paid date and set amount_paid = total_ttc
  if (status === 'payee') {
    // Fetch the invoice to get total_ttc
    const { data: existing } = await supabase
      .from('invoices')
      .select('total_ttc')
      .eq('id', id)
      .single()

    updateData.paid_date = new Date().toISOString().split('T')[0]
    if (existing) {
      updateData.amount_paid = existing.total_ttc
    }
  }

  const { data, error } = await supabase
    .from('invoices')
    .update(updateData)
    .eq('id', id)
    .select()
    .single()

  if (error) throw error
  return data as Invoice
}

// ---------------------------------------------------------------------------
// recordInvoicePayment - Record a payment (partial or full)
// ---------------------------------------------------------------------------
export async function recordInvoicePayment(
  id: string,
  amount: number,
  method: string,
  reference: string | null,
  currentAmountPaid: number,
  totalTtc: number,
): Promise<Invoice> {
  const totalPaid = Math.min(currentAmountPaid + amount, totalTtc)
  const newStatus: InvoiceStatus = totalPaid >= totalTtc ? 'payee' : 'partiellement_payee'

  const updateData: Record<string, unknown> = {
    status: newStatus,
    amount_paid: totalPaid,
    payment_method: method,
    payment_reference: reference,
  }

  if (newStatus === 'payee') {
    updateData.paid_date = new Date().toISOString().split('T')[0]
  }

  const { data, error } = await supabase
    .from('invoices')
    .update(updateData)
    .eq('id', id)
    .select()
    .single()

  if (error) throw error

  const invoice = data as Invoice

  // Create notification for payment
  try {
    const statusLabel = newStatus === 'payee' ? 'intégralement payée' : 'partiellement payée'
    // Get current user for notification target
    const { data: session } = await supabase.auth.getSession()
    const profileId = session?.session?.user?.id
    if (profileId) {
      await createNotification({
        profile_id: profileId,
        notification_type: 'success',
        title: `Paiement enregistré — ${invoice.reference}`,
        message: `La facture ${invoice.reference} a été ${statusLabel} (${amount.toFixed(2)} €)`,
        action_url: `/billing/invoices/${id}`,
        action_entity_type: 'invoice',
        action_entity_id: id,
      })
    }
  } catch {
    // Non-blocking
  }

  return invoice
}

// ---------------------------------------------------------------------------
// updateQuoteStatus
// ---------------------------------------------------------------------------
export async function updateQuoteStatus(
  id: string,
  status: QuoteStatus,
  additionalData?: Record<string, unknown>,
): Promise<Quote> {
  const updateData: Record<string, unknown> = { status, ...additionalData }

  if (status === 'accepte') {
    updateData.accepted_date = new Date().toISOString().split('T')[0]
  }

  if (status === 'brouillon') {
    updateData.accepted_date = null
    updateData.signing_token = null
    updateData.signature_url = null
    updateData.signed_at = null
    updateData.signer_ip = null
    updateData.signing_expires_at = null
  }

  const { data, error } = await supabase
    .from('quotes')
    .update(updateData)
    .eq('id', id)
    .select()
    .single()

  if (error) throw error

  const quote = data as Quote

  // Auto-create invoice when quote is sent
  if (status === 'envoye' && quote.client_id && !quote.converted_to_invoice_id) {
    try {
      const quoteWithLines = await getQuote(id)
      const today = new Date().toISOString().split('T')[0]

      const { data: client } = await supabase
        .from('clients')
        .select('payment_terms_days, default_payment_method')
        .eq('id', quote.client_id)
        .single()

      const paymentDays = client?.payment_terms_days ?? 30
      const dueDate = new Date()
      dueDate.setDate(dueDate.getDate() + paymentDays)

      const laborAmountHt = (quoteWithLines.lines ?? [])
        .filter((line: QuoteLine) => line.is_labor)
        .reduce((sum: number, line: QuoteLine) => sum + Number(line.total_ht), 0)

      const invoiceData = {
        client_id: quote.client_id,
        quote_id: id,
        chantier_id: null,
        title: quote.title,
        description: quote.description,
        status: 'emise' as InvoiceStatus,
        issue_date: today,
        due_date: dueDate.toISOString().split('T')[0],
        paid_date: null,
        subtotal_ht: quote.subtotal_ht,
        tva_rate: quote.tva_rate,
        tva_amount: quote.tva_amount,
        total_ttc: quote.total_ttc,
        discount_percentage: quote.discount_percentage,
        discount_amount: quote.discount_amount,
        amount_paid: 0,
        payment_method: (client?.default_payment_method ?? null) as Invoice['payment_method'],
        payment_reference: null,
        eligible_tax_credit: quote.eligible_tax_credit,
        labor_amount_ht: laborAmountHt,
        tax_credit_amount: quote.tax_credit_amount,
        net_after_credit: quote.net_after_credit,
        is_archived: false,
        pdf_url: null,
        exported_at: null,
        accounting_reference: null,
        created_by: null,
      }

      const invoiceLines = (quoteWithLines.lines ?? []).map((line: QuoteLine) => ({
        description: line.description,
        quantity: line.quantity,
        unit: line.unit,
        unit_price_ht: line.unit_price_ht,
        tva_rate: line.tva_rate,
        total_ht: line.total_ht,
        total_ttc: line.total_ttc,
        is_labor: line.is_labor,
        sort_order: line.sort_order,
      }))

      const invoice = await createInvoice(invoiceData, invoiceLines)

      // Link invoice to quote
      await supabase
        .from('quotes')
        .update({ converted_to_invoice_id: invoice.id })
        .eq('id', id)

      quote.converted_to_invoice_id = invoice.id
    } catch (err) {
      console.error('[updateQuoteStatus] Auto-invoice creation failed:', err)
    }
  }

  return quote
}

// ---------------------------------------------------------------------------
// sendQuoteEmail - Send quote via email using Edge Function
// ---------------------------------------------------------------------------
export async function sendQuoteEmail(quoteId: string): Promise<{ communication_id: string }> {
  const { data, error } = await supabase.functions.invoke('send-quote', {
    body: { quote_id: quoteId },
  })
  if (error) throw error
  return data as { communication_id: string }
}

// ---------------------------------------------------------------------------
// convertQuoteToInvoice - Accept quote and auto-generate invoice
// ---------------------------------------------------------------------------
export async function convertQuoteToInvoice(quoteId: string): Promise<{
  quote: Quote
  invoice: Invoice
}> {
  const quoteWithLines = await getQuote(quoteId)

  if (!quoteWithLines.client_id) {
    throw new Error('Le devis doit être associé à un client pour générer une facture.')
  }

  if (quoteWithLines.converted_to_invoice_id) {
    throw new Error('Ce devis a déjà été converti en facture.')
  }

  const today = new Date().toISOString().split('T')[0]

  // Fetch client payment config
  const { data: client } = await supabase
    .from('clients')
    .select('payment_terms_days, default_payment_method')
    .eq('id', quoteWithLines.client_id)
    .single()

  const paymentDays = client?.payment_terms_days ?? 30
  const dueDate = new Date()
  dueDate.setDate(dueDate.getDate() + paymentDays)

  // Calculate labor amount
  const laborAmountHt = (quoteWithLines.lines ?? [])
    .filter((line: QuoteLine) => line.is_labor)
    .reduce((sum: number, line: QuoteLine) => sum + Number(line.total_ht), 0)

  // Build invoice from quote
  const invoiceData = {
    client_id: quoteWithLines.client_id,
    quote_id: quoteId,
    chantier_id: null,
    title: quoteWithLines.title,
    description: quoteWithLines.description,
    status: 'emise' as InvoiceStatus,
    issue_date: today,
    due_date: dueDate.toISOString().split('T')[0],
    paid_date: null,
    subtotal_ht: quoteWithLines.subtotal_ht,
    tva_rate: quoteWithLines.tva_rate,
    tva_amount: quoteWithLines.tva_amount,
    total_ttc: quoteWithLines.total_ttc,
    discount_percentage: quoteWithLines.discount_percentage,
    discount_amount: quoteWithLines.discount_amount,
    amount_paid: 0,
    payment_method: (client?.default_payment_method ?? null) as Invoice['payment_method'],
    payment_reference: null,
    eligible_tax_credit: quoteWithLines.eligible_tax_credit,
    labor_amount_ht: laborAmountHt,
    tax_credit_amount: quoteWithLines.tax_credit_amount,
    net_after_credit: quoteWithLines.net_after_credit,
    is_archived: false,
    pdf_url: null,
    exported_at: null,
    accounting_reference: null,
    created_by: null,
  }

  // Build invoice lines from quote lines
  const invoiceLines = (quoteWithLines.lines ?? []).map((line: QuoteLine) => ({
    description: line.description,
    quantity: line.quantity,
    unit: line.unit,
    unit_price_ht: line.unit_price_ht,
    tva_rate: line.tva_rate,
    total_ht: line.total_ht,
    total_ttc: line.total_ttc,
    is_labor: line.is_labor,
    sort_order: line.sort_order,
  }))

  // Create invoice
  const invoice = await createInvoice(invoiceData, invoiceLines)

  // Update quote as accepted + link to invoice
  const { data: updatedQuote, error: updateError } = await supabase
    .from('quotes')
    .update({
      status: 'accepte',
      accepted_date: today,
      converted_to_invoice_id: invoice.id,
    })
    .eq('id', quoteId)
    .select()
    .single()

  if (updateError) throw updateError

  return {
    quote: updatedQuote as Quote,
    invoice,
  }
}

// ---------------------------------------------------------------------------
// getQuotes - Paginated list with optional filters
// ---------------------------------------------------------------------------
export async function getQuotes(
  filters: QuoteFilters = {},
): Promise<PaginatedResult<Quote>> {
  const {
    search,
    status,
    client_id,
    prospect_id,
    date_from,
    date_to,
    page = 1,
    pageSize = 25,
  } = filters

  let query = supabase
    .from('quotes')
    .select(
      '*, client:clients!client_id(id, first_name, last_name, company_name, siret, tva_number), prospect:prospects!prospect_id(id, first_name, last_name, company_name)',
      { count: 'exact' },
    )

  if (status) {
    query = query.eq('status', status)
  }

  if (client_id) {
    query = query.eq('client_id', client_id)
  }

  if (prospect_id) {
    query = query.eq('prospect_id', prospect_id)
  }

  if (date_from) {
    query = query.gte('issue_date', date_from)
  }

  if (date_to) {
    query = query.lte('issue_date', date_to)
  }

  if (search) {
    query = query.or(
      `reference.ilike.%${search}%,title.ilike.%${search}%`,
    )
  }

  // Pagination
  const from = (page - 1) * pageSize
  const to = from + pageSize - 1

  query = query
    .order('issue_date', { ascending: false })
    .range(from, to)

  const { data, error, count } = await query

  if (error) throw error

  return {
    data: (data ?? []) as Quote[],
    count: count ?? 0,
    page,
    pageSize,
    totalPages: Math.ceil((count ?? 0) / pageSize),
  }
}

// ---------------------------------------------------------------------------
// getQuote - Single quote with lines
// ---------------------------------------------------------------------------
export async function getQuote(id: string): Promise<Quote & { lines: QuoteLine[] }> {
  const { data, error } = await supabase
    .from('quotes')
    .select(`
      *,
      client:clients!client_id(id, first_name, last_name, company_name, email, phone, address_line1, postal_code, city, siret, tva_number),
      prospect:prospects!prospect_id(id, first_name, last_name, company_name, email),
      lines:quote_lines(*)
    `)
    .eq('id', id)
    .single()

  if (error) throw error

  // Sort lines by sort_order
  if (data.lines) {
    data.lines.sort((a: QuoteLine, b: QuoteLine) => a.sort_order - b.sort_order)
  }

  return data as Quote & { lines: QuoteLine[] }
}

// ---------------------------------------------------------------------------
// deleteQuote - Delete a quote and its lines (CASCADE handles lines)
// ---------------------------------------------------------------------------
export async function deleteQuote(id: string): Promise<void> {
  const { error } = await supabase
    .from('quotes')
    .delete()
    .eq('id', id)

  if (error) throw error
}

// ---------------------------------------------------------------------------
// createQuote - Create quote with its lines
// ---------------------------------------------------------------------------
export async function createQuote(
  quoteData: Omit<Quote, 'id' | 'reference' | 'created_at' | 'updated_at'>,
  lines: Omit<QuoteLine, 'id' | 'quote_id' | 'created_at'>[],
): Promise<Quote> {
  // Insert the quote (reference is auto-generated by the DB trigger)
  const { data: quote, error: quoteError } = await supabase
    .from('quotes')
    .insert({ ...quoteData, reference: '' })
    .select()
    .single()

  if (quoteError) throw quoteError

  // Insert all lines linked to the new quote
  if (lines.length > 0) {
    const linesWithQuoteId = lines.map((line) => ({
      ...line,
      quote_id: quote.id,
    }))

    const { error: linesError } = await supabase
      .from('quote_lines')
      .insert(linesWithQuoteId)

    if (linesError) {
      // Rollback: delete the quote if lines fail
      await supabase.from('quotes').delete().eq('id', quote.id)
      throw linesError
    }
  }

  return quote as Quote
}

// ---------------------------------------------------------------------------
// updateQuote - Update a quote and its lines (brouillon only)
// ---------------------------------------------------------------------------
export async function updateQuote(
  id: string,
  quoteData: Partial<Omit<Quote, 'id' | 'reference' | 'created_at' | 'updated_at'>>,
  lines?: Omit<QuoteLine, 'id' | 'quote_id' | 'created_at'>[],
): Promise<Quote> {
  const { data: quote, error: quoteError } = await supabase
    .from('quotes')
    .update(quoteData)
    .eq('id', id)
    .select()
    .single()

  if (quoteError) throw quoteError

  // If lines are provided, replace all existing lines
  if (lines) {
    const { error: deleteError } = await supabase
      .from('quote_lines')
      .delete()
      .eq('quote_id', id)

    if (deleteError) throw deleteError

    if (lines.length > 0) {
      const linesWithQuoteId = lines.map((line) => ({
        ...line,
        quote_id: id,
      }))

      const { error: linesError } = await supabase
        .from('quote_lines')
        .insert(linesWithQuoteId)

      if (linesError) throw linesError
    }
  }

  return quote as Quote
}

// ---------------------------------------------------------------------------
// generateFiscalAttestation - Create a fiscal attestation for a client/year
// ---------------------------------------------------------------------------
export async function generateFiscalAttestation(
  clientId: string,
  year: number,
): Promise<FiscalAttestation> {
  // 1. Fetch all paid invoices for this client in the given fiscal year
  //    that are eligible for tax credit
  const { data: invoices, error: invoicesError } = await supabase
    .from('invoices')
    .select('*')
    .eq('client_id', clientId)
    .eq('eligible_tax_credit', true)
    .eq('status', 'payee')
    .gte('issue_date', `${year}-01-01`)
    .lte('issue_date', `${year}-12-31`)

  if (invoicesError) throw invoicesError

  const invoiceList = invoices ?? []

  // 2. Calculate aggregated amounts
  const totalAmountTtc = invoiceList.reduce((sum, inv) => sum + Number(inv.total_ttc), 0)
  const totalLaborHt = invoiceList.reduce((sum, inv) => sum + Number(inv.labor_amount_ht), 0)
  const taxCreditAmount = invoiceList.reduce((sum, inv) => sum + Number(inv.tax_credit_amount), 0)
  const invoiceIds = invoiceList.map((inv) => inv.id)

  // 3. Fetch company settings (use defaults if not found)
  const { data: settings } = await supabase
    .from('settings')
    .select('key, value')
    .in('key', ['company_name', 'company_siret', 'company_address', 'company_agrement'])

  const settingsMap: Record<string, string> = {}
  if (settings) {
    settings.forEach((s) => {
      settingsMap[s.key] = String(s.value ?? '')
    })
  }

  // 4. Upsert the attestation (unique per client + fiscal year)
  const attestationData = {
    reference: `ATT-${year}-${clientId.substring(0, 8).toUpperCase()}`,
    client_id: clientId,
    fiscal_year: year,
    total_amount_ttc: totalAmountTtc,
    total_labor_ht: totalLaborHt,
    tax_credit_amount: taxCreditAmount,
    invoice_ids: invoiceIds,
    company_name: settingsMap['company_name'] ?? brand.name.split(' ')[0],
    company_siret: settingsMap['company_siret'] ?? '',
    company_address: settingsMap['company_address'] ?? '',
    company_agrement: settingsMap['company_agrement'] ?? null,
  }

  const { data, error } = await supabase
    .from('fiscal_attestations')
    .upsert(attestationData, { onConflict: 'client_id,fiscal_year' })
    .select()
    .single()

  if (error) throw error
  return data as FiscalAttestation
}

// ---------------------------------------------------------------------------
// getFiscalAttestations - List attestations, optionally filtered by year
// ---------------------------------------------------------------------------
export async function getFiscalAttestations(year?: number): Promise<FiscalAttestation[]> {
  let query = supabase
    .from('fiscal_attestations')
    .select('*, client:clients!client_id(id, first_name, last_name, company_name, email, address_line1, postal_code, city)')
    .order('fiscal_year', { ascending: false })
    .order('created_at', { ascending: false })

  if (year) {
    query = query.eq('fiscal_year', year)
  }

  const { data, error } = await query

  if (error) throw error
  return (data ?? []) as FiscalAttestation[]
}

// ---------------------------------------------------------------------------
// Eligible client for attestation (has paid invoices with tax credit in year)
// ---------------------------------------------------------------------------
export interface EligibleClient {
  client_id: string
  first_name: string
  last_name: string
  company_name: string | null
  email: string | null
  address_line1: string
  postal_code: string
  city: string
  invoice_count: number
  total_ttc: number
  total_labor_ht: number
}

export async function getEligibleClientsForAttestation(year: number): Promise<EligibleClient[]> {
  // Get all paid invoices with tax credit for the year
  const { data: invoices, error } = await supabase
    .from('invoices')
    .select('client_id, total_ttc, labor_amount_ht')
    .eq('eligible_tax_credit', true)
    .eq('status', 'payee')
    .gte('issue_date', `${year}-01-01`)
    .lte('issue_date', `${year}-12-31`)

  if (error) throw error
  if (!invoices || invoices.length === 0) return []

  // Group by client_id
  const byClient = new Map<string, { count: number; totalTtc: number; totalLaborHt: number }>()
  for (const inv of invoices) {
    const existing = byClient.get(inv.client_id) ?? { count: 0, totalTtc: 0, totalLaborHt: 0 }
    existing.count++
    existing.totalTtc += Number(inv.total_ttc)
    existing.totalLaborHt += Number(inv.labor_amount_ht)
    byClient.set(inv.client_id, existing)
  }

  // Fetch client details
  const clientIds = [...byClient.keys()]
  const { data: clients, error: clientError } = await supabase
    .from('clients')
    .select('id, first_name, last_name, company_name, email, address_line1, postal_code, city')
    .in('id', clientIds)

  if (clientError) throw clientError

  return (clients ?? []).map((c) => {
    const agg = byClient.get(c.id)!
    return {
      client_id: c.id,
      first_name: c.first_name,
      last_name: c.last_name,
      company_name: c.company_name,
      email: c.email,
      address_line1: c.address_line1,
      postal_code: c.postal_code,
      city: c.city,
      invoice_count: agg.count,
      total_ttc: agg.totalTtc,
      total_labor_ht: agg.totalLaborHt,
    }
  })
}

// ---------------------------------------------------------------------------
// Quote Templates — CRUD
// ---------------------------------------------------------------------------

export async function getQuoteTemplates(includeInactive = false): Promise<QuoteTemplate[]> {
  let query = supabase.from('quote_templates').select('*')
  if (!includeInactive) query = query.eq('is_active', true)
  query = query.order('name', { ascending: true })
  const { data, error } = await query
  if (error) throw error
  return (data ?? []) as QuoteTemplate[]
}

export async function getQuoteTemplate(id: string): Promise<QuoteTemplate> {
  const { data, error } = await supabase
    .from('quote_templates')
    .select('*')
    .eq('id', id)
    .single()
  if (error) throw error
  return data as QuoteTemplate
}

export async function createQuoteTemplate(
  input: Omit<QuoteTemplate, 'id' | 'created_at' | 'updated_at'>,
): Promise<QuoteTemplate> {
  const { data, error } = await supabase
    .from('quote_templates')
    .insert(input)
    .select()
    .single()
  if (error) throw error
  return data as QuoteTemplate
}

export async function updateQuoteTemplate(
  id: string,
  input: Partial<Omit<QuoteTemplate, 'id' | 'created_at' | 'updated_at'>>,
): Promise<QuoteTemplate> {
  const { data, error } = await supabase
    .from('quote_templates')
    .update(input)
    .eq('id', id)
    .select()
    .single()
  if (error) throw error
  return data as QuoteTemplate
}

export async function deleteQuoteTemplate(id: string): Promise<void> {
  const { error } = await supabase
    .from('quote_templates')
    .update({ is_active: false })
    .eq('id', id)
  if (error) throw error
}
